[project]
name = "concept-c2"
version = "0.1.0"
description = "C2 over Strava proof of concept"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.0",
    "requests>=2.32.3",
    "textual>=2.1.2",
]
